/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hujjpyomoycixxxvijtw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1ampweW9tb3ljaXh4eHZpanR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MjAyOTUsImV4cCI6MjA3OTE5NjI5NX0.J9vYBFfc12bC7T-0vxUFkwCO4TExBstoZLB-_HuI1oc"